name: Make Preview Game Build

on:
  workflow_dispatch:
    inputs:
      tracking_cache_key:
        description: "A unique key to cache the NPM build Artifact and enable retrieval via Cache API"
        required: true
        default: "key_001"
        type: string

jobs:
  build_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present 

      - name: Cache Result
        id : cache-build
        uses: actions/cache@v4
        with:
          path: "dist"
          key: ${{inputs.tracking_cache_key}}
